### ISSUE TITLE
Just a couple of pre-install questions

### ISSUE THREAD

**Issue by venteto** [manjaro/unity-for-manjaro#1]
Does this include global menu patches for Firefox, Thunderbid, Libre Office?

Will this hose my existing GNOME 43 installation if I try to install this side-by-side with it just to try it out? Or is everything namespaced in the file system to prevent Unity from overwriting any GNOME files?

**Comment by philmmanjaro** [comment]
It is better to use the provided ISO and test it either in a live session or in a Virtual Machine.
