### ISSUE TITLE
bug: Setup always crashes.

### ISSUE THREAD

**Issue by SunsetRay-SSR** [manjaro/unity-for-manjaro#9]
I've tried to install Manjaro Unity on VirtualBox. But when I click "Install Now", then Setup crashes.

**Comment by philmmanjaro** [comment]
What system settings did you use. RAM, CPU and so on?

**Comment by Kris2002047** [comment]
Host: VirtualBox1.2 on ThinkPad Edge E440
CPU: Intel Core i3-4000M@2.40GHz, 2vCPU in VBox.
RAM: 8GB on Host, 2GB in VM.
Boot Method: BIOS+MBR

**Comment by Kris2002047** [comment]
Host OS: Manjaro KDE 22.0.0 Sikaris.

**Comment by philmmanjaro** [comment]
Give the VM 4 GB of RAM ....

**Comment by Kris2002047** [comment]
I've given 4 GB of RAM and the setup haven't crashed anymore.
But the Setup still failed.
Setup says "Installation Successfully", but the OS can't boot up.
Disk: 65GiB Virtual Disk (SATA)

```shell
# /etc/fstab (Not fully follow the standard, just a part of the file)
/dev/sda1    /boot    ext4    #0-1GiB
/dev/sda2    /    ext4    #1-31GiB
/dev/sda3    none    extended    #31-65GiB
/dev/sda5    swap    swap    #31-35GiB
/dev/sda6    /home    ext4    #35-65GiB
# All of the partitions don't have any tag.
```

**Comment by SunsetRay-SSR** [comment]
The Problem has been solved, thank you!
